#############################################################################
# Makefile for building: Visualization.app/Contents/MacOS/Visualization
# Generated by qmake (2.01a) (Qt 4.8.7) on: Wed Jul 29 21:21:39 2015
# Project:  Visualization.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile Visualization.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -mmacosx-version-min=10.7 -O2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -mmacosx-version-min=10.7 -std=c++11 -Wall -Wextra -pedantic -O2 -arch x86_64 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.7/mkspecs/unsupported/macx-clang-libc++ -I. -I/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/lib/QtOpenGL.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.7/include -I. -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/usr/local/Cellar/qt/4.8.7/lib
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -mmacosx-version-min=10.7 -arch x86_64
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.7/lib -L/usr/local/Cellar/qt/4.8.7/lib -framework QtOpenGL -L/usr/local/Cellar/qt/4.8.7/lib -F/usr/local/Cellar/qt/4.8.7/lib -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.7

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		VisualizationWindow.cc \
		frame_buffer.cc \
		bitmap_loader.cc \
		histogram_cluster.cc \
		cluster_hash.cc moc_VisualizationWindow.cpp
OBJECTS       = main.o \
		VisualizationWindow.o \
		frame_buffer.o \
		bitmap_loader.o \
		histogram_cluster.o \
		cluster_hash.o \
		moc_VisualizationWindow.o
DIST          = /usr/local/Cellar/qt/4.8.7/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/include_source_dir.prf \
		Visualization.pro
QMAKE_TARGET  = Visualization
DESTDIR       = 
TARGET        = Visualization.app/Contents/MacOS/Visualization

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile Visualization.app/Contents/PkgInfo Visualization.app/Contents/Resources/empty.lproj Visualization.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) Visualization.app/Contents/MacOS/ || $(MKDIR) Visualization.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Visualization.pro  /usr/local/Cellar/qt/4.8.7/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt/4.8.7/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.7/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.7/lib/QtOpenGL.framework/QtOpenGL.prl \
		/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Visualization.pro
/usr/local/Cellar/qt/4.8.7/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/common/clang.conf:
/usr/local/Cellar/qt/4.8.7/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.7/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/shared.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.7/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.7/lib/QtOpenGL.framework/QtOpenGL.prl:
/usr/local/Cellar/qt/4.8.7/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.7/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Visualization.pro

Visualization.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) Visualization.app/Contents || $(MKDIR) Visualization.app/Contents 
	@$(DEL_FILE) Visualization.app/Contents/PkgInfo
	@echo "APPL????" >Visualization.app/Contents/PkgInfo
Visualization.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) Visualization.app/Contents/Resources || $(MKDIR) Visualization.app/Contents/Resources 
	@touch Visualization.app/Contents/Resources/empty.lproj
	
Visualization.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) Visualization.app/Contents || $(MKDIR) Visualization.app/Contents 
	@$(DEL_FILE) Visualization.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Visualization,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.7/mkspecs/unsupported/macx-clang-libc++/Info.plist.app >Visualization.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/Visualization1.0.0 || $(MKDIR) .tmp/Visualization1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Visualization1.0.0/ && $(COPY_FILE) --parents VisualizationWindow.h frame_buffer.h bitmap_loader.h histogram_cluster.h bitmap_image.hpp cluster_hash.h .tmp/Visualization1.0.0/ && $(COPY_FILE) --parents main.cc VisualizationWindow.cc frame_buffer.cc bitmap_loader.cc histogram_cluster.cc cluster_hash.cc .tmp/Visualization1.0.0/ && (cd `dirname .tmp/Visualization1.0.0` && $(TAR) Visualization1.0.0.tar Visualization1.0.0 && $(COMPRESS) Visualization1.0.0.tar) && $(MOVE) `dirname .tmp/Visualization1.0.0`/Visualization1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Visualization1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r Visualization.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_VisualizationWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_VisualizationWindow.cpp
moc_VisualizationWindow.cpp: VisualizationWindow.h
	/usr/local/Cellar/qt/4.8.7/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ VisualizationWindow.h -o moc_VisualizationWindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cc VisualizationWindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

VisualizationWindow.o: VisualizationWindow.cc VisualizationWindow.h \
		bitmap_loader.h \
		histogram_cluster.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualizationWindow.o VisualizationWindow.cc

frame_buffer.o: frame_buffer.cc frame_buffer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o frame_buffer.o frame_buffer.cc

bitmap_loader.o: bitmap_loader.cc bitmap_loader.h \
		frame_buffer.h \
		bitmap_image.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bitmap_loader.o bitmap_loader.cc

histogram_cluster.o: histogram_cluster.cc histogram_cluster.h \
		cluster_hash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o histogram_cluster.o histogram_cluster.cc

cluster_hash.o: cluster_hash.cc cluster_hash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cluster_hash.o cluster_hash.cc

moc_VisualizationWindow.o: moc_VisualizationWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_VisualizationWindow.o moc_VisualizationWindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

