######################################################################
# Automatically generated by qmake (2.01a) Fri Jul 10 18:04:00 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += VisualizationWindow.h sandbox/Travis/frame_buffer.h
SOURCES += main.cpp VisualizationWindow.cpp sandbox/Travis/frame_buffer.cc
QT += opengl
